database:
  connection:
    url: jdbc:postgresql://localhost:5432/monitoring_database
    username: postgres
    password: 4021
    driver: org.postgresql.Driver

liquibase:
  changeLogFile: liquibase/changelog-master.xml
  schemaName: migration_schema

security:
  tokenTime: 3600000
  secretKey: secretKey

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs.path: /api-docs
