version: '3.5'

services:
  postgres:
    image: postgres:15-alpine
    container_name: monitoring_database
    environment:
      POSTGRES_DB: monitoring_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4021
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres:
