###авторизация пользователя (user/admin)
POST http://localhost:8080/auth
Content-Type: application/json

{
  "username" : "user",
  "password" : "user"
}

###регистрация пользователя (user)
POST http://localhost:8080/register
Content-Type: application/json

{
  "username" : "newUser21",
  "password" : "newPassword"
}

###добавление нового счётчика (admin)
POST http://localhost:8080/devices
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNzd29yZCI6InVzZXIiLCJleHAiOjE3MDgyNzI3MjUsImlhdCI6MTcwODI2OTEyNSwidXNlcm5hbWUiOiJ1c2VyIn0.we0cc-gCC6k5lrJ9yzmsXd4BKMoWnbNlbXCZSzfn5_k

{
  "deviceName" : "newDevice"
}

###аудит действий пользователя (admin)
GET http://localhost:8080/audit
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNzd29yZCI6InVzZXIiLCJleHAiOjE3MDgyMjEwMTYsImlhdCI6MTcwODIxNzQxNiwidXNlcm5hbWUiOiJ1c2VyIn0.HLcU3XAOEeZVxx6Ac7iEuzrI_TgIjNZzmjlcSmSJc5A

###просмотр истории подачи показаний (admin/user)
GET http://localhost:8080/meterReadingsHistory
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNzd29yZCI6InVzZXIiLCJleHAiOjE3MDgzMDEwNDQsImlhdCI6MTcwODI5NzQ0NCwidXNlcm5hbWUiOiJ1c2VyIn0.D-M5mUnVTkTSn3fa1dAU_GEbHv0sMDbwb0b-H5ndoSM

###просмотр актуальных показаний счетчиков (admin/user)
GET http://localhost:8080/relevantMeterReadings
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNzd29yZCI6InVzZXIiLCJleHAiOjE3MDgzMDEwNDQsImlhdCI6MTcwODI5NzQ0NCwidXNlcm5hbWUiOiJ1c2VyIn0.D-M5mUnVTkTSn3fa1dAU_GEbHv0sMDbwb0b-H5ndoSM

###просмотр показаний счетчиков за конкретный месяц (admin/user)
GET http://localhost:8080/meterReadingsForMonth?month=1&year=2024
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNzd29yZCI6InVzZXIiLCJleHAiOjE3MDgzMDEwNDQsImlhdCI6MTcwODI5NzQ0NCwidXNlcm5hbWUiOiJ1c2VyIn0.D-M5mUnVTkTSn3fa1dAU_GEbHv0sMDbwb0b-H5ndoSM

###подача показаний (user)
POST http://localhost:8080/inputMeterReadings
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNzd29yZCI6Im5ld1Bhc3N3b3JkIiwiZXhwIjoxNzA4MzAxMTIyLCJpYXQiOjE3MDgyOTc1MjIsInVzZXJuYW1lIjoibmV3VXNlcjIxIn0.-7llVp_baborev5_NfbQKfgotY46J_cx79CbzlXyqxI

{"deviceValues": {
    "отопление": 1533.13,
    "холодная вода": 1335.8,
    "горячая вода": 1335.55
  }
}