###авторизация пользователя (user/admin)
POST http://localhost:8080/auth
Content-Type: application/json

{
  "username" : "user",
  "password" : "user"
}

###регистрация пользователя (user)
POST http://localhost:8080/register
Content-Type: application/json

{
  "username" : "newUser1",
  "password" : "newPassword"
}

###добавление нового счётчика (admin)
POST http://localhost:8080/devices
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNzd29yZCI6InVzZXIiLCJleHAiOjE3MDc2OTA5NDgsImlhdCI6MTcwNzY4NzM0OCwidXNlcm5hbWUiOiJ1c2VyIn0.f0m_4IDLz6LT8xZj6VjNinez2TAjmAZatFk4TDyyxd4

{
  "deviceName" : "newDevice"
}

###аудит действий пользователя (admin)
GET http://localhost:8080/audit
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNzd29yZCI6InVzZXIiLCJleHAiOjE3MDc2OTA5NDgsImlhdCI6MTcwNzY4NzM0OCwidXNlcm5hbWUiOiJ1c2VyIn0.f0m_4IDLz6LT8xZj6VjNinez2TAjmAZatFk4TDyyxd4

###просмотр истории подачи показаний (admin/user)
GET http://localhost:8080/meterReadingsHistory
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNzd29yZCI6InVzZXIiLCJleHAiOjE3MDc2OTA5NDgsImlhdCI6MTcwNzY4NzM0OCwidXNlcm5hbWUiOiJ1c2VyIn0.f0m_4IDLz6LT8xZj6VjNinez2TAjmAZatFk4TDyyxd4

###просмотр актуальных показаний счетчиков (admin/user)
GET http://localhost:8080/relevantMeterReadings
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNzd29yZCI6InVzZXIiLCJleHAiOjE3MDc2OTA5NDgsImlhdCI6MTcwNzY4NzM0OCwidXNlcm5hbWUiOiJ1c2VyIn0.f0m_4IDLz6LT8xZj6VjNinez2TAjmAZatFk4TDyyxd4

###просмотр показаний счетчиков за конкретный месяц (admin/user)
GET http://localhost:8080/meterReadingsForMonth?month=1&year=2024
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNzd29yZCI6InVzZXIiLCJleHAiOjE3MDc2OTA5NDgsImlhdCI6MTcwNzY4NzM0OCwidXNlcm5hbWUiOiJ1c2VyIn0.f0m_4IDLz6LT8xZj6VjNinez2TAjmAZatFk4TDyyxd4

###подача показаний (user)
POST http://localhost:8080/inputMeterReadings
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNzd29yZCI6InVzZXIiLCJleHAiOjE3MDc2OTA5NDgsImlhdCI6MTcwNzY4NzM0OCwidXNlcm5hbWUiOiJ1c2VyIn0.f0m_4IDLz6LT8xZj6VjNinez2TAjmAZatFk4TDyyxd4

{"deviceValues": {
    "отопление": 1533.13,
    "холодная вода": 1335.8,
    "горячая вода": 1335.55
  }
}