###авторизация пользователя (user/admin)
POST http://localhost:8080/auth
Content-Type: application/json

{
  "username" : "admin",
  "password" : "admin"
}

###регистрация пользователя (user)
POST http://localhost:8080/register
Content-Type: application/json

{
  "username" : "newUser21",
  "password" : "newPassword"
}

###добавление нового счётчика (admin)
POST http://localhost:8080/devices
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNzd29yZCI6ImFkbWluIiwiZXhwIjoxNzA4NjU1NzMwLCJpYXQiOjE3MDg2NTIxMzAsInVzZXJuYW1lIjoiYWRtaW4ifQ.lKWeINUODIGBj2ntWfX621Rk2efaliCsF_UsE-RhkNA

{
  "deviceName" : "newDevice"
}

###аудит действий пользователя (admin)
GET http://localhost:8080/audit
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNzd29yZCI6ImFkbWluIiwiZXhwIjoxNzA4Njg1MTE5LCJpYXQiOjE3MDg2ODE1MTksInVzZXJuYW1lIjoiYWRtaW4ifQ.SU8TayCTUjCYrE3vfRS93eogBb5bRsYuhvOPFTyPyOo

###просмотр истории подачи показаний (admin/user)
GET http://localhost:8080/meterReadings
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNzd29yZCI6ImFkbWluIiwiZXhwIjoxNzA4Njg1MTE5LCJpYXQiOjE3MDg2ODE1MTksInVzZXJuYW1lIjoiYWRtaW4ifQ.SU8TayCTUjCYrE3vfRS93eogBb5bRsYuhvOPFTyPyOo

###просмотр актуальных показаний счетчиков (admin/user)
GET http://localhost:8080/meterReadings/relevant
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNzd29yZCI6ImFkbWluIiwiZXhwIjoxNzA4Njg1MTE5LCJpYXQiOjE3MDg2ODE1MTksInVzZXJuYW1lIjoiYWRtaW4ifQ.SU8TayCTUjCYrE3vfRS93eogBb5bRsYuhvOPFTyPyOo

###просмотр показаний счетчиков за конкретный месяц (admin/user)
GET http://localhost:8080/meterReadings/forMonth?month=1&year=2024
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNzd29yZCI6ImFkbWluIiwiZXhwIjoxNzA4Njg1MTE5LCJpYXQiOjE3MDg2ODE1MTksInVzZXJuYW1lIjoiYWRtaW4ifQ.SU8TayCTUjCYrE3vfRS93eogBb5bRsYuhvOPFTyPyOo

###подача показаний (user)
POST http://localhost:8080/meterReadings
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNzd29yZCI6InVzZXIiLCJleHAiOjE3MDg2NTQ2OTEsImlhdCI6MTcwODY1MTA5MSwidXNlcm5hbWUiOiJ1c2VyIn0.WApFwHPF5yaCU1t2aHycG9PYNk3asWNpEUvPzAlmZ2c

{"deviceValues": {
    "отопление": 1533.13,
    "холодная вода": 1335.8,
    "горячая вода": 1335.55
  }
}